if(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
  if(${CMAKE_SYSTEM_PROCESSOR} MATCHES "i386")
    SET(MYOPTFLAGS "-march=nocona -O3 -pipe -fomit-frame-pointer -funroll-loops -ftree-vectorize -ftracer -ffast-math")
  elseif(${CMAKE_SYSTEM_PROCESSOR} MATCHES "powerpc")
    SET(MYOPTFLAGS "-mtune=powerpc -maltivec -mabi=altivec -mcpu=7400 -O3 -pipe -fomit-frame-pointer -funroll-loops -ftree-vectorize -ftracer -ffast-math")
  endif(${CMAKE_SYSTEM_PROCESSOR} MATCHES "i386")
endif(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
if(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
  if(${CMAKE_SYSTEM_PROCESSOR} MATCHES "i686")
    SET(MYOPTFLAGS "-march=pentium4 -O3 -pipe -fomit-frame-pointer -funroll-loops -ftree-vectorize -ftracer -ffast-math")
  elseif(${CMAKE_SYSTEM_PROCESSOR} MATCHES "Cell Broadband Engine, altivec supported")
    SET(MYOPTFLAGS "-O3 -pipe -mtune=970 -mcpu=970 -mabi=altivec -fomit-frame-pointer -funroll-loops -ftree-vectorize -ftracer -ffast-math")
  elseif(${CMAKE_SYSTEM_PROCESSOR} MATCHES "AMD")
    SET(MYOPTFLAGS "-march=k8 -O3 -pipe -fomit-frame-pointer -funroll-loops -ftree-vectorize -ftracer -ffast-math")
  elseif(${CMAKE_SYSTEM_PROCESSOR} MATCHES "x86_64")
    SET(MYOPTFLAGS "-march=k8 -O3 -pipe -fomit-frame-pointer -funroll-loops -ftree-vectorize -ftracer -ffast-math")
  endif(${CMAKE_SYSTEM_PROCESSOR} MATCHES "i686")
endif(${CMAKE_SYSTEM_NAME} MATCHES "Linux")